version: '3.1'

services:
  # currency-exchange:
  #   depends_on: 
  #     - db
  #   image: currency-exchange
  #   ports:
  #     - 8081:8080
  
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    env_file:
      - .env
    ports:
      - 5672:5672
      - 15672:15672