version: '3.1'

services:
  currency-exchange:
    image: currency-exchange
    depends_on: 
      - currency-exchange-db
    ports:
      - 8081:8080
  
  currency-exchange-db:
    image: postgres
    env_file:
      - .env
    ports:
      - 5432:5432

  rabbitmq:
    image: rabbitmq:3-management
    env_file:
      - .env
    ports:
      - 5672:5672
      - 15672:15672
